import { Event } from "./types"

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Peña Folklórica en Balcarce",
    venue: "La Casona del Molino",
    date: "2026-04-25",
    time: "21:00",
    category: "penas",
    price: 5000,
    image: "/placeholder.svg?height=450&width=300",
    description: "Una noche de música folklórica tradicional con artistas locales. Empanadas y vino patero incluido.",
    address: "Calle Balcarce 980, Salta",
    ticketUrl: "https://example.com/tickets",
    noiseLevel: 60,
    vibe: "familiar",
    isFeatured: true,
  },
  {
    id: "2",
    title: "Noche Electrónica",
    venue: "Club Mandarine",
    date: "2026-04-26",
    time: "00:00",
    category: "boliches",
    price: 8000,
    image: "/placeholder.svg?height=450&width=300",
    description: "Los mejores DJs de la zona sur te esperan para una noche inolvidable.",
    address: "Av. Paraguay 1250, Salta",
    ticketUrl: "https://example.com/tickets",
    noiseLevel: 95,
    vibe: "adultos",
    isFeatured: true,
  },
  {
    id: "3",
    title: "Feria Gastronómica Regional",
    venue: "Parque San Martín",
    date: "2026-04-27",
    time: "11:00",
    category: "ferias",
    price: "gratis",
    image: "/placeholder.svg?height=450&width=300",
    description: "Degustación de platos típicos salteños: locro, empanadas, tamales y más.",
    address: "Parque San Martín, Salta",
    noiseLevel: 40,
    vibe: "familiar",
    isFeatured: true,
  },
  {
    id: "4",
    title: "Romeo y Julieta - Ballet",
    venue: "Teatro Provincial",
    date: "2026-04-28",
    time: "20:30",
    category: "teatro",
    price: 12000,
    image: "/placeholder.svg?height=450&width=300",
    description: "La clásica obra de Shakespeare interpretada por el Ballet de Salta.",
    address: "Zuviría 70, Salta",
    ticketUrl: "https://example.com/tickets",
    noiseLevel: 30,
    vibe: "familiar",
    isFeatured: true,
  },
  {
    id: "5",
    title: "Taller de Cerámica Diaguita",
    venue: "Centro Cultural América",
    date: "2026-04-29",
    time: "16:00",
    category: "talleres",
    price: 3500,
    image: "/placeholder.svg?height=450&width=300",
    description: "Aprende las técnicas ancestrales de cerámica de los pueblos originarios.",
    address: "Mitre 23, Salta",
    noiseLevel: 20,
    vibe: "familiar",
  },
  {
    id: "6",
    title: "Cine al Aire Libre: Clásicos Argentinos",
    venue: "Plaza 9 de Julio",
    date: "2026-04-30",
    time: "21:00",
    category: "cine",
    price: "gratis",
    image: "/placeholder.svg?height=450&width=300",
    description: "Proyección de películas clásicas del cine argentino bajo las estrellas.",
    address: "Plaza 9 de Julio, Salta",
    noiseLevel: 35,
    vibe: "exterior",
  },
  {
    id: "7",
    title: "Peña del Cuchi Leguizamón",
    venue: "Boliche de Balderrama",
    date: "2026-05-01",
    time: "22:00",
    category: "penas",
    price: 6000,
    image: "/placeholder.svg?height=450&width=300",
    description: "Homenaje al gran compositor salteño con músicos invitados.",
    address: "San Martín 1126, Salta",
    ticketUrl: "https://example.com/tickets",
    noiseLevel: 55,
    vibe: "familiar",
  },
  {
    id: "8",
    title: "After Office Latino",
    venue: "Macro Club",
    date: "2026-05-02",
    time: "19:00",
    category: "boliches",
    price: 4000,
    image: "/placeholder.svg?height=450&width=300",
    description: "Arranca el finde con los mejores hits latinos y 2x1 en tragos.",
    address: "España 502, Salta",
    ticketUrl: "https://example.com/tickets",
    noiseLevel: 80,
    vibe: "adultos",
  },
  {
    id: "9",
    title: "Feria de Artesanos",
    venue: "Mercado Artesanal",
    date: "2026-05-03",
    time: "09:00",
    category: "ferias",
    price: "gratis",
    image: "/placeholder.svg?height=450&width=300",
    description: "Artesanías en cuero, plata y tejidos tradicionales de la región.",
    address: "Av. San Martín 2555, Salta",
    noiseLevel: 30,
    vibe: "exterior",
  },
  {
    id: "10",
    title: "Stand Up Comedy: Humor Norteño",
    venue: "La Vieja Estación",
    date: "2026-05-04",
    time: "21:30",
    category: "teatro",
    price: 7000,
    image: "/placeholder.svg?height=450&width=300",
    description: "Una noche de risas con los mejores comediantes del NOA.",
    address: "Av. Belgrano 1090, Salta",
    ticketUrl: "https://example.com/tickets",
    noiseLevel: 65,
    vibe: "adultos",
  },
  {
    id: "11",
    title: "Taller de Cocina Criolla",
    venue: "Escuela de Gastronomía",
    date: "2026-05-05",
    time: "10:00",
    category: "talleres",
    price: 4500,
    image: "/placeholder.svg?height=450&width=300",
    description: "Aprende a preparar locro, humita y empanadas salteñas.",
    address: "Caseros 476, Salta",
    noiseLevel: 25,
    vibe: "familiar",
  },
  {
    id: "12",
    title: "Ciclo de Cine Independiente",
    venue: "Cine Victoria",
    date: "2026-05-06",
    time: "19:00",
    category: "cine",
    price: 2500,
    image: "/placeholder.svg?height=450&width=300",
    description: "Muestra de cortometrajes de directores salteños emergentes.",
    address: "Alvarado 447, Salta",
    ticketUrl: "https://example.com/tickets",
    noiseLevel: 20,
    vibe: "adultos",
  },
  {
    id: "13",
    title: "Fiesta de la Pachamama",
    venue: "Campo Quijano",
    date: "2026-05-07",
    time: "12:00",
    category: "ferias",
    price: "gratis",
    image: "/placeholder.svg?height=450&width=300",
    description: "Celebración tradicional con ofrendas a la Madre Tierra, música y comida típica.",
    address: "Campo Quijano, Salta",
    noiseLevel: 50,
    vibe: "exterior",
    isFeatured: true,
  },
  {
    id: "14",
    title: "Noche de Tango",
    venue: "La Glorieta",
    date: "2026-05-08",
    time: "22:00",
    category: "penas",
    price: 5500,
    image: "/placeholder.svg?height=450&width=300",
    description: "Milonga con orquesta en vivo y clase de tango para principiantes.",
    address: "Güemes 401, Salta",
    noiseLevel: 50,
    vibe: "adultos",
  },
  {
    id: "15",
    title: "Festival de Música Andina",
    venue: "Anfiteatro Municipal",
    date: "2026-05-09",
    time: "18:00",
    category: "penas",
    price: 3000,
    image: "/placeholder.svg?height=450&width=300",
    description: "Sikuris, charangos y quenas en un encuentro de música tradicional.",
    address: "Av. Entre Ríos s/n, Salta",
    ticketUrl: "https://example.com/tickets",
    noiseLevel: 70,
    vibe: "exterior",
  },
]
