import { Event } from "./types"

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "PeÃ±a FolklÃ³rica en Balcarce",
    venue: "La Casona del Molino",
    date: "2026-04-25",
    time: "21:00",
    category: "penas",
    price: 5000,
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&h=900&fit=crop",
    description: "Una noche de mÃºsica folklÃ³rica tradicional con artistas locales. Empanadas y vino patero incluido.",
    address: "Calle Balcarce 980, Salta",
    ticketUrl: "https://example.com/tickets",
    vibe: "familiar",
    isFeatured: true,
  },
  {
    id: "2",
    title: "Noche ElectrÃ³nica",
    venue: "Club Mandarine",
    date: "2026-04-26",
    time: "00:00",
    category: "boliches",
    price: 8000,
    image: "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&h=900&fit=crop",
    description: "Los mejores DJs de la zona sur te esperan para una noche inolvidable.",
    address: "Av. Paraguay 1250, Salta",
    ticketUrl: "https://example.com/tickets",
    vibe: "adultos",
    isFeatured: true,
  },
  {
    id: "3",
    title: "Feria GastronÃ³mica Regional",
    venue: "Parque San MartÃ­n",
    date: "2026-04-27",
    time: "11:00",
    category: "ferias",
    price: "gratis",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=900&fit=crop",
    description: "DegustaciÃ³n de platos tÃ­picos salteÃ±os: locro, empanadas, tamales y mÃ¡s.",
    address: "Parque San MartÃ­n, Salta",
    vibe: "familiar",
    isFeatured: true,
  },
  {
    id: "4",
    title: "Romeo y Julieta - Ballet",
    venue: "Teatro Provincial",
    date: "2026-04-28",
    time: "20:30",
    category: "teatro",
    price: 12000,
    image: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=600&h=900&fit=crop",
    description: "La clÃ¡sica obra de Shakespeare interpretada por el Ballet de Salta.",
    address: "ZuvirÃ­a 70, Salta",
    ticketUrl: "https://example.com/tickets",
    vibe: "familiar",
    isFeatured: true,
  },
  {
    id: "5",
    title: "Taller de CerÃ¡mica Diaguita",
    venue: "Centro Cultural AmÃ©rica",
    date: "2026-04-29",
    time: "16:00",
    category: "talleres",
    price: 3500,
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&h=900&fit=crop",
    description: "Aprende las tÃ©cnicas ancestrales de cerÃ¡mica de los pueblos originarios.",
    address: "Mitre 23, Salta",
    vibe: "familiar",
  },
  {
    id: "6",
    title: "Cine al Aire Libre: ClÃ¡sicos Argentinos",
    venue: "Plaza 9 de Julio",
    date: "2026-04-30",
    time: "21:00",
    category: "cine",
    price: "gratis",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&h=900&fit=crop",
    description: "ProyecciÃ³n de pelÃ­culas clÃ¡sicas del cine argentino bajo las estrellas.",
    address: "Plaza 9 de Julio, Salta",
    vibe: "exterior",
  },
  {
    id: "7",
    title: "PeÃ±a del Cuchi LeguizamÃ³n",
    venue: "Boliche de Balderrama",
    date: "2026-05-01",
    time: "22:00",
    category: "penas",
    price: 6000,
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=900&fit=crop",
    description: "Homenaje al gran compositor salteÃ±o con mÃºsicos invitados.",
    address: "San MartÃ­n 1126, Salta",
    ticketUrl: "https://example.com/tickets",
    vibe: "familiar",
  },
  {
    id: "8",
    title: "After Office Latino",
    venue: "Macro Club",
    date: "2026-05-02",
    time: "19:00",
    category: "boliches",
    price: 4000,
    image: "https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&h=900&fit=crop",
    description: "Arranca el finde con los mejores hits latinos y 2x1 en tragos.",
    address: "EspaÃ±a 502, Salta",
    ticketUrl: "https://example.com/tickets",
    vibe: "adultos",
  },
  {
    id: "9",
    title: "Feria de Artesanos",
    venue: "Mercado Artesanal",
    date: "2026-05-03",
    time: "09:00",
    category: "ferias",
    price: "gratis",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=900&fit=crop",
    description: "ArtesanÃ­as en cuero, plata y tejidos tradicionales de la regiÃ³n.",
    address: "Av. San MartÃ­n 2555, Salta",
    vibe: "exterior",
  },
  {
    id: "10",
    title: "Stand Up Comedy: Humor NorteÃ±o",
    venue: "La Vieja EstaciÃ³n",
    date: "2026-05-04",
    time: "21:30",
    category: "teatro",
    price: 7000,
    image: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=600&h=900&fit=crop",
    description: "Una noche de risas con los mejores comediantes del NOA.",
    address: "Av. Belgrano 1090, Salta",
    ticketUrl: "https://example.com/tickets",
    vibe: "adultos",
  },
  {
    id: "11",
    title: "Taller de Cocina Criolla",
    venue: "Escuela de GastronomÃ­a",
    date: "2026-05-05",
    time: "10:00",
    category: "talleres",
    price: 4500,
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&h=900&fit=crop",
    description: "Aprende a preparar locro, humita y empanadas salteÃ±as.",
    address: "Caseros 476, Salta",
    vibe: "familiar",
  },
  {
    id: "12",
    title: "Ciclo de Cine Independiente",
    venue: "Cine Victoria",
    date: "2026-05-06",
    time: "19:00",
    category: "cine",
    price: 2500,
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&h=900&fit=crop",
    description: "Muestra de cortometrajes de directores salteÃ±os emergentes.",
    address: "Alvarado 447, Salta",
    ticketUrl: "https://example.com/tickets",
    vibe: "adultos",
  },
  {
    id: "13",
    title: "Fiesta de la Pachamama",
    venue: "Campo Quijano",
    date: "2026-05-07",
    time: "12:00",
    category: "ferias",
    price: "gratis",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=900&fit=crop",
    description: "CelebraciÃ³n tradicional con ofrendas a la Madre Tierra, mÃºsica y comida tÃ­pica.",
    address: "Campo Quijano, Salta",
    vibe: "exterior",
    isFeatured: true,
  },
  {
    id: "14",
    title: "Noche de Tango",
    venue: "La Glorieta",
    date: "2026-05-08",
    time: "22:00",
    category: "penas",
    price: 5500,
    image: "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=600&h=900&fit=crop",
    description: "Milonga con orquesta en vivo y clase de tango para principiantes.",
    address: "GÃ¼emes 401, Salta",
    vibe: "adultos",
  },
  {
    id: "15",
    title: "Festival de MÃºsica Andina",
    venue: "Anfiteatro Municipal",
    date: "2026-05-09",
    time: "18:00",
    category: "penas",
    price: 3000,
    image: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&h=900&fit=crop",
    description: "Sikuris, charangos y quenas en un encuentro de mÃºsica tradicional.",
    address: "Av. Entre RÃ­os s/n, Salta",
    ticketUrl: "https://example.com/tickets",
    vibe: "exterior",
  },
]
